// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Center_Call_FullMethodName = "/proto.Center/Call"
)

// CenterClient is the client API for Center service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterClient interface {
	Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallResp, error)
}

type centerClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterClient(cc grpc.ClientConnInterface) CenterClient {
	return &centerClient{cc}
}

func (c *centerClient) Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallResp, error) {
	out := new(CallResp)
	err := c.cc.Invoke(ctx, Center_Call_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterServer is the server API for Center service.
// All implementations must embed UnimplementedCenterServer
// for forward compatibility
type CenterServer interface {
	Call(context.Context, *CallReq) (*CallResp, error)
	mustEmbedUnimplementedCenterServer()
}

// UnimplementedCenterServer must be embedded to have forward compatible implementations.
type UnimplementedCenterServer struct {
}

func (UnimplementedCenterServer) Call(context.Context, *CallReq) (*CallResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedCenterServer) mustEmbedUnimplementedCenterServer() {}

// UnsafeCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterServer will
// result in compilation errors.
type UnsafeCenterServer interface {
	mustEmbedUnimplementedCenterServer()
}

func RegisterCenterServer(s grpc.ServiceRegistrar, srv CenterServer) {
	s.RegisterService(&Center_ServiceDesc, srv)
}

func _Center_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Center_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServer).Call(ctx, req.(*CallReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Center_ServiceDesc is the grpc.ServiceDesc for Center service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Center_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Center",
	HandlerType: (*CenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Center_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
